seed: 100
device: "cuda"
input:
  path: "datasets"
  batch_size: 100
  num_classes: 10
  num_features: 310
model:
  peer_normalization: 0.03
  momentum: 0.9
  hidden_dim: 200
  num_layers: 3
  goodness_type: "sum_of_squares"
training:
  epochs: 50
  learning_rate: 0.0003
  weight_decay: 0.0003
  momentum: 0.9
  downstream_learning_rate: 0.01
  downstream_weight_decay: 0.003
  val_idx: -1
  final_test: true